spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://127.0.0.1:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.attendancecheck: DEBUG